    void translate(){
    ACCOLADE_DROITE.setLocal("","");
    ACCOLADE_GAUCHE.setLocal("","");
    ACCOLADE_SUPERIEURE.setLocal("","");
    ALPHA_MAJUSCULE.setLocal("alfa mayúscula",".Alfa");
    ALPHA_MINUSCULE.setLocal("alfa minúscula",".alfa");
    ANGLE.setLocal("","");
    APPARTIENT_A.setLocal("","");
    AU_CARRE.setLocal("al cuadrado",".alcuad", "");
    AU_CUBE.setLocal("al cubo",".alcubo", "");
    BETA_MAJUSCULE.setLocal("beta mayúscula",".Beta");
    BETA_MINUSCULE.setLocal("beta minúscula",".beta");
    CHI_MAJUSCULE.setLocal("ji mayúscula",".Ji");
    CHI_MINUSCULE.setLocal("ji minúscula",".ji");
    CONTIENT.setLocal("","");
    CROCHET_DROIT.setLocal("","");
    CROCHET_GAUCHE.setLocal("","");
    DELTA_MAJUSCULE.setLocal("delta mayúscula ",".Delta");
    DELTA_MINUSCULE.setLocal("delta minúscula",".delta");
    DERIVEE_PARTIELLE.setLocal("","");
    DIVISE.setLocal("","","");
    DIVISE_PAR.setLocal("","","");
    DZETA_MAJUSCULE.setLocal("dseta mayúscula",".Dseta");
    DZETA_MINUSCULE.setLocal("dseta minúscula ",".dseta");
    EGAL_CERCLE.setLocal("","","");
    EN_EXPOSANT.setLocal("","");
    EN_INDICE.setLocal("","");
    EN_INDICE_ET_EXPOSANT.setLocal("","","");
    ENSEMBLE_COMPLEXES.setLocal("");
    ENSEMBLE_ENTIERS_NATURELS.setLocal("");
    ENSEMBLE_ENTIERS_RELATIFS.setLocal("");
    ENSEMBLE_RATIONNELS.setLocal("");
    ENSEMBLE_REELS.setLocal("");
    ENSEMBLE_REELS_OU_COMPLEXES.setLocal("");
    ENSEMBLE_VIDE.setLocal("","","");
    EPSILON_MAJUSCULE.setLocal("épsilon mayúscula",".Epsilon");
    EPSILON_MINUSCULE.setLocal("épsilon minúscula",".epsilon");
    EST_APPROXIMATIVEMENT_EGAL_A.setLocal("","");
    EST_ASSOCIE_A.setLocal("","","");
    EST_DIFFERENT_DE.setLocal("","","");
    EST_EGAL_A.setLocal("","","");
    EST_EQUIVALENT_A.setLocal("","");
    EST_INCLUS_DANS.setLocal("","");
    ET.setLocal("","");
    ETA_MAJUSCULE.setLocal("eta mayúscula",".Eta");
    ETA_MINUSCULE.setLocal("eta minúscula",".eta");
    ETOILE_CERCLE.setLocal("","");
    EXPOSANT.setLocal("","","");
    FLECHE_A_DOUBLE_SENS.setLocal("","");
    FLECHE_DROITE.setLocal("","");
    FLECHE_GAUCHE.setLocal("","");
    FOIS.setLocal("por",".por","");
    FOIS_CERCLE.setLocal("por círculo",".por@");
    FRACTION.setLocal("fracción",".frac","");
    GAMMA_MAJUSCULE.setLocal("gamma mayúscula",".Gamma");
    GAMMA_MINUSCULE.setLocal("gamma minúscula",".gamma");
    I.setLocal("","");
    IL_EXISTE.setLocal("","");
    IMPLIQUE.setLocal("","","");
    INCONNU_001.setLocal("","");
    INDICE.setLocal("","","");
    INDICE_ET_EXPOSANT.setLocal("","");
    INFERIEUR_OU_EGAL_A.setLocal("","","");
    INFINI.setLocal("","","");
    INTEGRALE.setLocal("","","");
    INTEGRALE_CIRCULAIRE.setLocal("","");
    INTER.setLocal("","");
    IOTA_MAJUSCULE.setLocal("iota mayúscula",".Iota");
    IOTA_MINUSCULE.setLocal("iota minúscula",".iota");
    J.setLocal("","");
    KAPPA_MAJUSCULE.setLocal("kappa mayúscula",".Kappa");
    KAPPA_MINUSCULE.setLocal("kappa minúscula",".kappa");
    LAMBDA_MAJUSCULE.setLocal("lambda mayúscula",".Lambda");
    LAMBDA_MINUSCULE.setLocal("lambda minúscula",".lambda");
    MATRICE_CARREE_D_ORDRE_2.setLocal("","");
    MATRICE_CARREE_D_ORDRE_3.setLocal("","");
    MATRICE_CARREE_D_ORDRE_N.setLocal("","");
    MATRICE_UNITE_D_ORDRE_2.setLocal("","");
    MATRICE_UNITE_D_ORDRE_3.setLocal("","");
    MATRICE_UNITE_D_ORDRE_N.setLocal("","");
    MOINS.setLocal("menos",".menos");
    MOINS_PLUS.setLocal("menos o más","");
    MU_MAJUSCULE.setLocal("mi mayúscula",".Mi");
    MU_MINUSCULE.setLocal("mi minúscula",".mi");
    N_APPARTIENT_PAS_A.setLocal("","");
    NE_DIVISE_PAS.setLocal("","","");
    NOMBRE_00_CERCLE.setLocal("numero cero círculo",".0@");
    NOMBRE_01_CERCLE.setLocal("numero uno círculo",".1@");
    NOMBRE_02_CERCLE.setLocal("numero dos círculo",".2@");
    NOMBRE_03_CERCLE.setLocal("numero tres círculo",".3@");
    NOMBRE_04_CERCLE.setLocal("numero cuatro círculo",".4@");
    NOMBRE_05_CERCLE.setLocal("numero cinco círculo",".5@");
    NOMBRE_06_CERCLE.setLocal("numero seís círculo",".6@");
    NOMBRE_07_CERCLE.setLocal("numero siete círculo",".7@");
    NOMBRE_08_CERCLE.setLocal("numero ocho círculo",".8@");
    NOMBRE_09_CERCLE.setLocal("numero nueve círculo",".9@");
    NOMBRE_10_CERCLE.setLocal("numero díes círculo",".10@");
    NON.setLocal("","");
    NORME.setLocal("","");
    NU_MAJUSCULE.setLocal("ni mayúscula",".Ni");
    NU_MINUSCULE.setLocal("ni minúscula",".ni");
    OMEGA_MAJUSCULE.setLocal("omega mayúscula",".Omega");
    OMEGA_MINUSCULE.setLocal("omega minúscula",".omega");
    OMICRON_MAJUSCULE.setLocal("ómicron mayúscula",".Omicron");
    OMICRON_MINUSCULE.setLocal("ómicron minúscula",".omicron");
    OU.setLocal("","");
    PARENTHESE_DROITE.setLocal("","");
    PARENTHESE_GAUCHE.setLocal("","");
    PHI_MAJUSCULE.setLocal("fi mayúscula",".Fi");
    PHI_MINUSCULE.setLocal("fi minúscula",".fi");
    PI_MAJUSCULE.setLocal("pi mayúscula",".Pi");
    PI_MINUSCULE.setLocal("pi minúscula",".pi");
    PLUS.setLocal("más",".mas");
    PLUS_MOINS.setLocal("más o menos","");
    POINT_CERCLE.setLocal("","");
    POUR_MILLE.setLocal("","");
    PRODUIT.setLocal("","");
    PSI_MAJUSCULE.setLocal("psi mayúscula",".Psi");
    PSI_MINUSCULE.setLocal("psi minúscula",".psi");
    QUATRE_TIERS.setLocal("s");
    QUEL_QUE_SOIT.setLocal("","");
    RACINE_CARREE.setLocal("raíz cuadrada",".rcuad","");
    RADICAL.setLocal("","");
    REPRESENTE.setLocal("","");
    RHO_MAJUSCULE.setLocal("rho mayúscula",".Rho");
    RHO_MINUSCULE.setLocal("rho minúscula",".rho");
    ROND.setLocal("","","");
    ROND_CERCLE.setLocal("","");
    SEULEMENT_SI.setLocal("","","");
    SI_ET_SEULEMENT_SI.setLocal("","", "");
    SIGMA_MAJUSCULE.setLocal("sigma mayúscula",".Sigma");
    SIGMA_MINUSCULE.setLocal("sigma minúscula",".sigma");
    SOMME.setLocal("","");
    SOMME_DIRECTE.setLocal("","","");
    SUPERIEUR_OU_EGAL_A.setLocal("","","");
    SUR.setLocal("","");
    TAU_MAJUSCULE.setLocal("tau mayúscula",".Tau");
    TAU_MINUSCULE.setLocal("tau minúscula",".tau");
    THETA_MAJUSCULE.setLocal("theta mayúscula",".Theta");
    THETA_MINUSCULE.setLocal("theta minúscula",".theta");
    TRES_INFERIEUR_A.setLocal("","");
    TRES_SUPERIEUR_A.setLocal("","");
    UNION.setLocal("","");
    UN_DEMI.setLocal("un medio");
    UN_TIERS.setLocal("un tercio");
    UPSILON_MAJUSCULE.setLocal("ípsilon mayúscula",".ipsilon");
    UPSILON_MINUSCULE.setLocal("ípsilon minúscula",".ipsilon");
    XI_MAJUSCULE.setLocal("xi mayúscula",".Xi");
    XI_MINUSCULE.setLocal("xi minúscula",".xi");
    }
